### ISSUE TITLE
Issue with Visualize command with CGImageRef

### ISSUE THREAD

**Issue by mohamede1945** [facebook/chisel#100]
Whenever I try the visualize a CGImageRef. I got the following error:

```
error: error: cannot initialize a parameter of type 'CGImage *' with an lvalue of type 'CGImageRef' (aka 'CGImage *')
error: 1 errors parsing expression
Traceback (most recent call last):
  File "/usr/local/opt/chisel/libexec/fblldb.py", line 81, in runCommand
    command.run(args, options)
  File "/usr/local/Cellar/chisel/1.2.0/libexec/commands/FBVisualizationCommands.py", line 138, in run
    _visualize(arguments[0])
  File "/usr/local/Cellar/chisel/1.2.0/libexec/commands/FBVisualizationCommands.py", line 109, in _visualize
    _showImage('(id)[UIImage imageWithCGImage:' + target + ']')
  File "/usr/local/Cellar/chisel/1.2.0/libexec/commands/FBVisualizationCommands.py", line 37, in _showImage
    imageBytesStartAddress = fb.evaluateExpression('(void *)[(id)' + imageDataAddress + ' bytes]')
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

Using Xcode 6.3.2

**Comment by kastiglione** [comment]
Do you know what image format the underlying `CGImageRef` uses?

The `visualize` command is making use of `UIImagePNGRepresentation`, which the documentation states:

> A data object containing the PNG data, or `nil` if there was a problem generating the data. _This function may return `nil` if the image has no data or if the underlying `CGImageRef` contains data in an unsupported bitmap format._

**Comment by mohamede1945** [comment]
You are correct. My data is in JPG format. I'll close it as invalid.

**Comment by kastiglione** [comment]
I should look into what it would take to support other formats.
