### ISSUE TITLE
chisel only works fine once

### ISSUE THREAD

**Issue by adad184** [facebook/chisel#102]
I installed **chisel** correctly, and it work fine when i debug first time.
but when i run debugging again, chisel can not be loaded. So i have to restart the xcode to make it works again.

please tell me how to fix this? 

the scripts works like this
```objc
//first time
(lldb) visualize someview

//second time
(lldb) visualize someview
error: 'visualize' is not a valid command.
```

**Comment by dostrander** [comment]
@adad184 When you mean "debug first time" do you mean when you first start your debugging session it only works one time (ex: one breakpoint it works, the next it doesn't). Or it only works for one debugging session(the next time you push run it doesn't work) ?

**Comment by adad184** [comment]
it works only for one debugging session.  When i rerun the debugging session, it's failed.

**Comment by idrisr** [comment]
@adad184 are you still having this issue? Can you run `command script list` when `visualize` is no longer working? Also please post the contents of your `~/.lldbinit`.

**Comment by adad184** [comment]
it seems the issue was gone  after i upgrade my Xcode to release version.

my `~/.lldbinit` content is 

> command script import "~/Library/Application Support/Realm/rlm_lldb.py" --allow-reload
> command script import /usr/local/opt/chisel/libexec/fblldb.py

**Comment by idrisr** [comment]
@adad184 . looks like this issue can be closed.

**Comment by adad184** [comment]
sure  :)
