### ISSUE TITLE
Add command to enable writing to const types

### ISSUE THREAD

**Issue by kastiglione** [facebook/chisel#115]
@rohan-mehta seeded this idea. When a variable is `const`, lldb will respect that and prevent assignment to the variable. Perhaps we could add a chisel convenience command that does this for the user:

```
(lldb) e CGFloat *p = (CGFloat *)&constVariable; *p = 1.0
```

**Comment by idrisr** [comment]
Is that valid syntax? I get an error when running that...

```
>>>> lldb >>>> e
Enter expressions, then terminate with an empty line to evaluate:
  1: CGFloat *p = (CGFloat *)&constVariable
  2: *p = 1.0
  3:
error: use of undeclared identifier 'constVariable'
```

**Comment by kastiglione** [comment]
`constVariable` refers to the variable that is `const`, that you want to edit. For example, given this definition:

```objc
const CGFloat iconWidth = fullWidth - labelWidth - padding * 2;
```

If you wanted to reassign `iconWidth` in lldb, you could use the above statement, except with `iconWidth` instead of `constVariable`. Note however, we tried this with x86, but not x86-64, or on arm.
