### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by idrisr** [facebook/chisel#118]
What are the plans for doing a new release? there's been 50+ commits since 1.2 and some bug fixes so it seems we should do one soon.

**Comment by kastiglione** [comment]
Done! https://github.com/facebook/chisel/releases/tag/1.3.0

I'll open a pull request to update homebrew.

**Comment by kastiglione** [comment]
https://github.com/Homebrew/homebrew/pull/44839

**Comment by idrisr** [comment]
great, thanks!

**Comment by kastiglione** [comment]
:cake:
