### ISSUE TITLE
Print NSData as text

### ISSUE THREAD

**Issue by ZevEisenberg** [facebook/chisel#123]
I often get `NSData` representing UTF-8-encoded strings back from APIs. What I want essentially comes down to a shortcut for:

```objc
po [[NSString alloc] initWithData:(NSData *)self.mutableData encoding:NSUTF8StringEncoding
```

But it would need to coexist with the existing feature to print `NSData` representing an image. It might also be nice to have an option to copy the resulting text to the clipboard, or open it in `$EDITOR` or maybe even a configurable app (e.g. TextMate or CocoaJSONEditor).

Posting this here to get feedback on what kind of features/options people would want. Would you want other encodings besides UTF-8? How would the interface for that work? If there is interest and some consensus on the interface, I can probably submit a PR.

**Comment by mmmulani** [comment]
I would stick to UTF-8, IMO the other encoding don't really matter.

I like the idea of copying to clipboard, opening in editor, etc. but maybe have that as a separate command, so you could chain them like:

> pstr dataVariable
$12 = @"..."
> copy $12
<$12 is now on the clipboard>
> editor $12
<open $EDITOR with $12>

**Comment by kastiglione** [comment]
We have a `pdata` added by @bartoszj in #83.

**Comment by ZevEisenberg** [comment]
Cool, that looks like exactly what I was hoping for.

**Comment by kastiglione** [comment]
Thanks for submitting ideas! Keep em coming :sparkler:
