### ISSUE TITLE
Where to create .lldbinit file

### ISSUE THREAD

**Issue by anbarasu0504** [facebook/chisel#127]
Its specified in the documentation as

**Alternatively, download chisel and add the following line to your ~/.lldbinit file. If it doesn't exist, create it.**

I really don't know where to locate this .lldbinit file. 

I downloaded .lldbinit file and placed it in my project folder like .gitignore but it dint work. 

Sorry for this newbie question, but I really done know where to locate this or create and put this.

**Comment by idrisr** [comment]
We're all newbs once, not an issue. 

`~/` refers to your home directory. You can put your `.lldbinit` in other places, but then Xcode won't automatically load it. If you put it somewhere other than `~/.lldbinit`, you need to source it in Xcode in the LLDB session like this:

`(lldb) command source <mypath>/.llbinit` 

where `<mypath>` is replaced by the path of your `.lldbinit`

**Comment by anbarasu0504** [comment]
Thanks a lot :)  got it working :+1:

**Comment by kastiglione** [comment]
Thanks @idrisr

**Comment by wangzcOvO** [comment]
Thanks a lot ! @idrisr
