### ISSUE TITLE
 short option can't works well in command 'fvc'

### ISSUE THREAD

**Issue by lianchengjiang** [facebook/chisel#130]
full option can works well, bug if i use short option, it show nothing.

(lldb) fvc -n=viewcontroller
(lldb) fvc --name=viewcontroller
0x7fd01a90f310 ViewController

**Comment by kastiglione** [comment]
@lianchengjiang Very sorry for the late reply. The short option expects a space, not an equal sign, before the argument.

For example:

```
(lldb) fvc -n viewcontroller
```

**Comment by lianchengjiang** [comment]
ok, thank you for your reply
