### ISSUE TITLE
Command pviews doesn't work in Xcode 7.3

### ISSUE THREAD

**Issue by kenny1269** [facebook/chisel#151]
i just install chisel, i try other commands like pvc work fine, but pviews doesn't work, nothing print and nothing running...can someone help?

**Comment by khramtsoff** [comment]
https://github.com/facebook/chisel/issues/149
Fixed in Xcode 7.3.1

**Comment by kastiglione** [comment]
Thanks for the report @kenny1269. As @khramtsoff pointed to, the problem (which is an Xcode bug) is fixed in 7.3.1.
