### ISSUE TITLE
chisel pview did not print anything

### ISSUE THREAD

**Issue by Ambtion** [facebook/chisel#153]
I use chisel(1.4) ,pviews a view ,and it did not print anything

**Comment by kastiglione** [comment]
Which version of Xcode are you using?

**Comment by esam091** [comment]
The same happens to me, using Xcode 7.3.

**Comment by alanzeino** [comment]
#149

**Comment by kastiglione** [comment]
@Ambtion @esam091 There was a bug with Xcode 7.3 that caused these output issues. The bug is fixed in Xcode 7.3.1, which came out yesterday.

**Comment by Ambtion** [comment]
I up xcode to 7.3.1, and it ok,thanks
