### ISSUE TITLE
script: /usr/local/Cellar/chisel/1.4.0/libexec/fblldb.py: Permission denied

### ISSUE THREAD

**Issue by EI3ven** [facebook/chisel#157]
1，brew install chisel
2，echo  command script import /usr/local/Cellar/chisel/1.4.0/libexec/fblldb.py >> ~/.lldbinit
3，source ~/.lldbinit 
Script started, output file is import
script: /usr/local/Cellar/chisel/1.4.0/libexec/fblldb.py: Permission denied

**Comment by kastiglione** [comment]
Thanks for the report. I haven't seen this before. Can you run:

```sh
ls -l  /usr/local/Cellar/chisel/1.4.0/libexec/fblldb.py
```

and paste the results here?

Have you tried running `brew doctor`?

**Comment by kastiglione** [comment]
Oh, I just re-read your steps, and see that step 3 is probably your problem.

```
source ~/.lldbinit
```

You don't want/need to do this. The `.lldbinit` file is for lldb, not for your shell.

**Comment by EI3ven** [comment]
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your Xcode (7.3) is outdated
Please update to Xcode 7.3.1.
Xcode can be updated from the App Store.




ls -l /usr/local/Cellar/chisel/1.4.0/libexec/fblldb.py
-rw-r--r--  1 admin  admin  5298 Jan  6 05:52 /usr/local/Cellar/chisel/1.4.0/libexec/fblldb.py



becasue I use lldb command like pvc pviews not have  a log

**Comment by kastiglione** [comment]
> becasue I use lldb command like pvc pviews not have a log

I'm not sure what you mean by "not have a log"

**Comment by EI3ven** [comment]
(lldb) pviews
(lldb)

**Comment by EI3ven** [comment]
(lldb) pviews
(lldb)

**Comment by kastiglione** [comment]
Are you using Xcode 7.3? It shipped with a known bug that prevented output of python commands. Upgrade to 7.3.1 to get a working Xcode.

**Comment by EI3ven** [comment]
OK ,THX
