### ISSUE TITLE
slowanim cannot work

### ISSUE THREAD

**Issue by cysgit** [facebook/chisel#161]
it always returns error when i use slowanim.
like below
```
(lldb) slowanim
error: unexpected '@' in program
error: 1 errors parsing expression
```
why?
Should I put the breakpoint during an animation? Actually, I have tried that and got the same error.
Also, I tried 

```
(lldb) slowanim 0.2
error: unexpected '@' in program
error: 1 errors parsing expression
```
got the same error.

Could anyone tell me what can I do?

**Comment by kastiglione** [comment]
Thanks for the report. I'll investigate.

**Comment by kastiglione** [comment]
@cysgit Do you recall whether you ran `slowanim` from a Swift project?

**Comment by Cellane** [comment]
Not the original poster but I observed this error even in a project that didn't have a single line of Swift code in it – nor in CocoaPods' dependencies.

**Comment by kastiglione** [comment]
Thanks @Cellane, I'll look into this now.

**Comment by kastiglione** [comment]
@Cellane how is your Chisel installed? which version are you using? I just tried with a recent checkout and I can't reproduce this error.

**Comment by Cellane** [comment]
Unfortunately I'm not at my work computer anymore, but I have Chisel installed by Homebrew and I run `brew update` and `brew upgrade` fairly regularly, so I'd assume I have a fairly recent one – but I'll check in detail on Monday and if I'll still experience the issue, I'll try to produce a sample project (not sure if it'll help anything, but it can't harm either, right?)

**Comment by kastiglione** [comment]
Thanks for the details! Chisel is due for a new release and related homebrew update, so I will do that, and then when you upgrade, can you report back here if the problem has been fixed? If it's not fixed up a new release, then we can try a sample project.

**Comment by kastiglione** [comment]
https://github.com/Homebrew/homebrew-core/pull/4336

**Comment by Cellane** [comment]
Updated to 1.5.0 and… actually having more issues than before I'm afraid. This is the new output of `slowanim`:

    (lldb) slowanim
    error: 'eobjc' is not a valid command.
    error: Unrecognized command 'eobjc'.

But other commands are now having issues as well:

    (lldb) border self.deviceNameTextField
    Traceback (most recent call last):
      File "/usr/local/opt/chisel/libexec/fblldb.py", line 83, in runCommand
        command.run(args, options)
      File "/usr/local/Cellar/chisel/1.5.0/libexec/commands/FBDisplayCommands.py", line 69, in run
        obj = fb.evaluateInputExpression(args[0])
    AttributeError: 'module' object has no attribute 'evaluateInputExpression'

Or:

    (lldb) hide self.deviceNameTextField
    error: 'eobjc' is not a valid command.
    error: Unrecognized command 'eobjc'.
    error: 'eobjc' is not a valid command.
    error: Unrecognized command 'eobjc'.

Or:

    (lldb) visualize self.view
    Traceback (most recent call last):
      File "/usr/local/opt/chisel/libexec/fblldb.py", line 83, in runCommand
        command.run(args, options)
      File "/usr/local/Cellar/chisel/1.5.0/libexec/commands/FBVisualizationCommands.py", line 183, in run
        _visualize(arguments[0])
      File "/usr/local/Cellar/chisel/1.5.0/libexec/commands/FBVisualizationCommands.py", line 157, in _visualize
        _showLayer('[(id)' + target + ' layer]')
      File "/usr/local/Cellar/chisel/1.5.0/libexec/commands/FBVisualizationCommands.py", line 111, in _showLayer
        fb.evaluateEffect('UIGraphicsBeginImageContextWithOptions(' + size + ', NO, 0.0)')
    AttributeError: 'module' object has no attribute 'evaluateEffect'

I'm still running on Xcode 7.3.1 if that changes anything.

**Comment by Cellane** [comment]
Ouch, never mind! Restarting Xcode fixed everything, apologies! `slowanim` now seems to be working just fine, along with all the other commands!

**Comment by kastiglione** [comment]
Thanks! Glad it's working.
