### ISSUE TITLE
fb.EvaluateExpression returning NoneType

### ISSUE THREAD

**Issue by jasonmay** [facebook/chisel#162]
Using the master branch, I am working on a custom command for printing out ANSI sequences of a grid.

The very first step is to try to evaluate an expression, any expression, just to get started. I'm following what the other commands do, and I it complains that there is no value. This happens with anything I put in as an expression, a string, a regular variable, etc.

I also think this is why none of my commands work.

```python
#!/usr/bin/python
# Example file with custom commands, located at /magical/commands/example.py

import lldb
import fblldbbase as fb
import pprint

def lldbcommands():
  return [ PrintGrid() ]

class PrintGrid(fb.FBCommand):
  def name(self):
    return 'pgrid'

  def description(self):
    return 'Print grid information based on specific grid'

  def run(self, arguments, options):
    # It's a good habit to explicitly cast the type of all return
    # values and arguments. LLDB can't always find them on its own.

    v = fb.evaluateExpressionValue("[1, 2, 3]")
    pprint.pprint(v)
    pprint.pprint(v.description)
    pprint.pprint(v.summary)
    pprint.pprint(v.value)
    lldbOutput = v.GetObjectDescription()
    pprint.pprint(lldbOutput)

    if lldbOutput is None:
        lldb.debugger.HandleCommand('po "we failed"\n')
```

The relevant log output from lldb:

```
    [ClangASTImporter] Forgetting destination (ASTContext*)0x7f91968a6000
    [ClangASTImporter] Forgetting source->dest (ASTContext*)0x7f91968a6000->(ASTContext*)0x7f91c3973c00
[(null) 0x7f9196964600] checking for FormatManager revisions. ValueObject rev: 0 - Global rev: 4888
[(null) 0x7f9196964600] checking for FormatManager revisions. ValueObject rev: 0 - Global rev: 4888
SBValue(0x7f9196964600)::GetValue() => NULL
[(null) 0x7f9196964600] checking for FormatManager revisions. ValueObject rev: 0 - Global rev: 4888
[(null) 0x7f9196964600] checking for FormatManager revisions. ValueObject rev: 0 - Global rev: 4888
SBValue(0x7f9196964600)::GetSummary() => NULL
** [SBFrame::EvaluateExpression] Expression result is (null), summary (null) **
SBFrame(0x7f918c22b3f0)::EvaluateExpression (expr="[1, 2, 3]") => SBValue(0x7f9196964600) (execution result=2)
[(null) 0x7f9196964600] checking for FormatManager revisions. ValueObject rev: 0 - Global rev: 4888
SBError(0x7f91aa67f160)::Fail () => 1
SBError(0x7f91aa67f160)::GetError () => 0x00000002
[(null) 0x7f9196964600] checking for FormatManager revisions. ValueObject rev: 0 - Global rev: 4888
[(null) 0x7f9196964600] checking for FormatManager revisions. ValueObject rev: 0 - Global rev: 4888
SBValue(0x7f9196964600)::GetObjectDescription() => NULL
[(null) 0x7f9196964600] checking for FormatManager revisions. ValueObject rev: 0 - Global rev: 4888
[(null) 0x7f9196964600] checking for FormatManager revisions. ValueObject rev: 0 - Global rev: 4888
SBValue(0x7f9196964600)::GetSummary() => NULL
[(null) 0x7f9196964600] checking for FormatManager revisions. ValueObject rev: 0 - Global rev: 4888
[(null) 0x7f9196964600] checking for FormatManager revisions. ValueObject rev: 0 - Global rev: 4888
SBValue(0x7f9196964600)::GetValue() => NULL
[(null) 0x7f9196964600] checking for FormatManager revisions. ValueObject rev: 0 - Global rev: 4888
[(null) 0x7f9196964600] checking for FormatManager revisions. ValueObject rev: 0 - Global rev: 4888
SBValue(0x7f9196964600)::GetObjectDescription() => NULL
SBCommandInterpreter::SBCommandInterpreter (interpreter=0x0) => SBCommandInterpreter(0x0)
SBDebugger(0x7f919ed00000)::GetCommandInterpreter () => SBCommandInterpreter(0x7f91b0eca230)
SBCommandInterpreter(0x7f91b0eca230)::HandleCommand (command="po "we failed"
", SBCommandReturnObject(0x7f91cb0cd980), add_to_history=0)
Processing command: po "we failed"

HandleCommand, cmd_obj : 'expression'
HandleCommand, (revised) command_string: 'expression -O  --  "we failed"
'
HandleCommand, wants_raw_input:'True'
HandleCommand, command line after removing command name(s): '-O  --  "we failed"
'
== [UserExpression::Evaluate] Parsing expression "we failed"
 ==
SwiftUserExpression::ScanContext()
  [SUE::SC] Compilation unit is swift
```

**Comment by jasonmay** [comment]
side note, how do I get stdout (`print`, `pprint` statements, etc.) to show up in the Xcode console? I can only see if it I run `lldb` from a terminal but I can't really test this from a context-less lldb shell.

**Comment by kastiglione** [comment]
> side note, how do I get stdout

Which version of Xcode are you using?

**Comment by kastiglione** [comment]
There's a known bug in Xcode 7.3 (mentioned in the release notes) that python I/O is broken. This might be one of the problems you're bumping up against.

Further, Chisel is definitely less mature in terms of Swift support, which you're using here. Chisel needs to get better in this regard, and I haven't been doing any Swift work myself so I'm happy to get feedback on Swift issues.

Recently I made some changes that introduced `evaluateInputExpression` which is like `evaluateExpressionValue` except with regard to which language is expected for the input expression. `evaluateExpressionValue` uses ObjC++ no matter what, but `evaluateInputExpression` uses the language of the current frame, which is maybe what you want for your case since it's probably Swift. It would be possible to refactor `evaluateExpressionValue` to take an optional argument that let's the caller say which language the expression is in. In your case this would be `eLanguageTypeSwift`.

**Comment by jasonmay** [comment]
I am using Xcode 7.3, so I'm sure that is the issue.

I will certainly play around with Swift in mind, at least with some modules made from scratch, learning my way as I go. Once I learn where things diverge, I will happily provide feedback in the form of PRs.

I discovered that the frame could retrieve `grid` but not `grid[0]` which I _think_ are both valid in Swift and ObjC++ but I could be wrong (I also may be wrongly basing this on the assumption that it would work exactly like `po grid[0]`, which works). Either way, this may be a limitation of my knowledge of what I can evaluate from the frame context (not much information out there on it), and not really a limitation of this framework (the simplest `lldb.frame.EvaluateExpression("grid[0]").getObjectDescription()` would fail when `"grid"` passed in returned the expected values).

Next time I have some spare time I'll give `evaluateInputExpression` a shot; thanks!

**Comment by kastiglione** [comment]
It seems like this issue can be closed, but that's not the case and there's more to discuss, please re-open it.
