### ISSUE TITLE
Issue visualizing swift views

### ISSUE THREAD

**Issue by deepumukundan** [facebook/chisel#163]
I am getting the below error when trying to visualize views in swift code. Been having similar issues with swift code for a longer time now. 

error: error: use of undeclared identifier 'titleView'
error: 1 errors parsing expression
Traceback (most recent call last):
  File "/usr/local/opt/chisel/libexec/fblldb.py", line 79, in runCommand
    command.run(args, options)
  File "/usr/local/Cellar/chisel/1.4.0/libexec/commands/FBVisualizationCommands.py", line 183, in run
    _visualize(arguments[0])
  File "/usr/local/Cellar/chisel/1.4.0/libexec/commands/FBVisualizationCommands.py", line 151, in _visualize
    if fb.evaluateBooleanExpression('(unsigned long)CFGetTypeID((CFTypeRef)' + target + ') == (unsigned long)CGImageGetTypeID()'):
  File "/usr/local/opt/chisel/libexec/fblldbbase.py", line 70, in evaluateBooleanExpression
    return (int(evaluateIntegerExpression('(BOOL)(' + expression + ')', printErrors)) != 0)
  File "/usr/local/opt/chisel/libexec/fblldbbase.py", line 62, in evaluateIntegerExpression
    output = evaluateExpression('(int)(' + expression + ')', printErrors).replace('\'', '')
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by kastiglione** [comment]
Thanks for the report. I think the problem you're hitting might be fixed in `master`. If it's not fixed in `master`, I should definitely make sure to fix it. Are you willing to try installing `master` and reporting back?

**Comment by deepumukundan** [comment]
Sure. I just got master (so I was using brew to install chisel, so I went inside /usr/local/opt/chisel and replaced the contents inside libexec folder with the ones I got from master). The error seemed to have changed now (atleast the last part of it). Does the below help?

(lldb) visualize view
Traceback (most recent call last):
  File "/usr/local/opt/chisel/libexec/fblldb.py", line 83, in runCommand
    command.run(args, options)
  File "/usr/local/Cellar/chisel/1.4.0/libexec/commands/FBVisualizationCommands.py", line 183, in run
    _visualize(arguments[0])
  File "/usr/local/Cellar/chisel/1.4.0/libexec/commands/FBVisualizationCommands.py", line 157, in _visualize
    _showLayer('[(id)' + target + ' layer]')
  File "/usr/local/Cellar/chisel/1.4.0/libexec/commands/FBVisualizationCommands.py", line 111, in _showLayer
    fb.evaluateEffect('UIGraphicsBeginImageContextWithOptions(' + size + ', NO, 0.0)')
AttributeError: 'module' object has no attribute 'evaluateEffect'

**Comment by kastiglione** [comment]
> 'module' object has no attribute '`evaluateEffect`'

This is saying it can't find the function `evaluateEffect`, which could be a result of how you "replaced the contents".

Using Chisel straight from git is fairly straight forward. This would eliminate any homebrew issues.

Steps:

1. Clone the chisel repo (`git clone https://github.com/facebook/chisel.git`)
2. Edit your `~/.lldbinit` to include this line: `command script import ~/path/to/chisel/fblldb.py'

**Comment by deepumukundan** [comment]
Thanks @kastiglione That fixed the problem. Much appreciated!

I should have just used the clone I downloaded in the first place. I was trying to not edit my .lldbinit which I push to github shared between my machines.

**Comment by kastiglione** [comment]
Glad it's working!

**Comment by H0icky** [comment]
When I try to visualize a UIImage.I get the error mention above.
I had already used the latest chisel. But it still get the error

error: error: use of undeclared identifier 'CFTypeRef'
...
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by kastiglione** [comment]
@H0icky I missed your comment. I'm trying to fix the issue in #171.

**Comment by H0icky** [comment]
OK, I think they are the similar problem.
