### ISSUE TITLE
why my command pjson is not work others is ok?

### ISSUE THREAD

**Issue by wmfgithub** [facebook/chisel#164]
pjson dic
error: error: cannot initialize a parameter of type 'NSData * _Nonnull' with an rvalue of type 'long'
note: passing argument to parameter 'data' here
error: 1 errors parsing expression
None

**Comment by kastiglione** [comment]
Thanks for submitting this issue @wmfgithub. I think this problem has been fixed in master. You could try using Chisel via a git checkout, and check that `pjson` has been fixed.
