### ISSUE TITLE
using comman 'pjson' to print a NSDictionary unsuccessfully

### ISSUE THREAD

**Issue by tripleCC** [facebook/chisel#165]
My code is below:
` NSDictionary *dict = @{@"key" : @"value"};   `                                                                                     
   ` (void)dict;`
I make a break at line 2.  And then I input 'pjson dict' to xcode debug area. 
The error was printed:

`error: error: cannot initialize a parameter of type 'NSData * _Nonnull' with an rvalue of type 'long'
note: passing argument to parameter 'data' here
error: 1 errors parsing expression
None`

**Comment by kastiglione** [comment]
Thanks for the report.

Can you try the changes in pull request #166? You can do this by cloning the `pjson-types` branch like so:

```
git clone -b pjson-types https://github.com/facebook/chisel.git
```

Then edit your `~/.lldbinit` to use the path of where you checked out the `psjon-types` branch.

**Comment by kastiglione** [comment]
Thanks again for submitting this issue. This problem should be fixed in master now.

**Comment by tripleCC** [comment]
Nice job! And when I can install the fixed version of chisel  from brew?

**Comment by kastiglione** [comment]
There's no set schedule for brew updates. I should probably update the chisel formula to allow installing from master. I'll see about doing a brew update sooner than later.

**Comment by Ashton-W** [comment]
https://github.com/Homebrew/homebrew-core/pull/3292

**Comment by kastiglione** [comment]
@Ashton-W nice!
