### ISSUE TITLE
Chisel improperly recognizing convenience vars

### ISSUE THREAD

**Issue by joshavant** [facebook/chisel#169]
**Chisel version:** 1.5.0
**LLDB version:** lldb-360.1.38
**Xcode version:** 8b5

**Reproduction:**

0: Have a `Main.storyboard` file in the main bundle, with a view controller w/ identifier `viewController`.

1:

```
(lldb) settings set target.language swift
(lldb) expr import UIKit
(lldb) expr var $avc = UIStoryboard(name: "Main", bundle: Bundle.main).instantiateViewController(withIdentifier: "viewController")
(lldb) po $avc
<Foo.UIViewController: 0x7fb369f06650>


(lldb) present $avc
error: error: use of undeclared identifier '$avc'
error: use of undeclared identifier '$avc'
Traceback (most recent call last):
  File "/usr/local/opt/chisel/libexec/fblldb.py", line 83, in runCommand
    command.run(args, options)
  File "/usr/local/Cellar/chisel/1.5.0/libexec/commands/FBDisplayCommands.py", line 221, in run
    viewControllerHelpers.presentViewController(args[0])
  File "/usr/local/opt/chisel/libexec/fblldbviewcontrollerhelpers.py", line 18, in presentViewController
    if fb.evaluateBooleanExpression('%s != nil && ((BOOL)[(id)%s isKindOfClass:(Class)[UIViewController class]])' % (vc, vc)):
  File "/usr/local/opt/chisel/libexec/fblldbbase.py", line 84, in evaluateBooleanExpression
    return (int(evaluateIntegerExpression('(BOOL)(' + expression + ')', printErrors)) != 0)
  File "/usr/local/opt/chisel/libexec/fblldbbase.py", line 76, in evaluateIntegerExpression
    output = evaluateExpression('(int)(' + expression + ')', printErrors).replace('\'', '')
AttributeError: 'NoneType' object has no attribute 'replace'
```

I believe Chisel should be properly interpreting the convenience var `$avc` here, but seems not to. Any ideas if this is a problem with the user or the framework?

Related: #150

**Comment by joshavant** [comment]
Sidenote to those who may find this bug in the future:
It appears sticking to Objective-C syntax here will cause things to work as expected:
```
expr UIViewController *$avc = (UIViewController *)[[UIStoryboard storyboardWithName:@"Main" bundle:nil] instantiateViewControllerWithIdentifier:@"viewController"]
present $avc
```

**Comment by alanzeino** [comment]
Ah, Swift. When I wrote the dismiss and present, I only tested using Objective-C.

**Comment by kastiglione** [comment]
I wonder if variable definitions are bound to a language? It's not unreasonable to think that the `$avc` defined in Swift is not available when evaluating with objc, since not all Swift types and semantics translate into objc.

**Comment by kastiglione** [comment]
Most commands now evaluate their input using the current language. I haven't tried `present` specifically, but any commands that don't evaluate input in the current language will be soon switched over.
