### ISSUE TITLE
Visualize command gives error: use of undeclared identifier 'CFTypeRef'

### ISSUE THREAD

**Issue by ZevEisenberg** [facebook/chisel#170]
This may be related to https://github.com/facebook/chisel/issues/163

When I run `vi label` were `label` is some `UILabel`, I'm getting this:

```
(lldb) vi label
error: error: use of undeclared identifier 'CFTypeRef'
error: use of undeclared identifier 'label'
Traceback (most recent call last):
  File "/Users/zev/Projects/chisel/fblldb.py", line 83, in runCommand
    command.run(args, options)
  File "/Users/zev/Projects/chisel/commands/FBVisualizationCommands.py", line 183, in run
    _visualize(arguments[0])
  File "/Users/zev/Projects/chisel/commands/FBVisualizationCommands.py", line 151, in _visualize
    if fb.evaluateBooleanExpression('(unsigned long)CFGetTypeID((CFTypeRef)' + target + ') == (unsigned long)CGImageGetTypeID()'):
  File "/Users/zev/Projects/chisel/fblldbbase.py", line 84, in evaluateBooleanExpression
    return (int(evaluateIntegerExpression('(BOOL)(' + expression + ')', printErrors)) != 0)
  File "/Users/zev/Projects/chisel/fblldbbase.py", line 76, in evaluateIntegerExpression
    output = evaluateExpression('(int)(' + expression + ')', printErrors).replace('\'', '')
AttributeError: 'NoneType' object has no attribute 'replace'
```

Here's a screenshot. As you can see, `label` is a `UILabel` that is currently in scope.

![screen shot 2016-09-28 at 6 28 25 pm](https://cloud.githubusercontent.com/assets/464574/18934827/29fe0a06-85aa-11e6-81c5-7e32752a7ecc.png)

I tried with both the latest release from Homebrew and `master`. I'm using Xcode 8.0 and Swift 3.

Here's a trivial sample project which you can use to reproduce this bug: https://cl.ly/hbOV

**Comment by kastiglione** [comment]
Thanks for the report! If you're able to try out the `fix-visualize-in-swft` branch (from #171), that would be great. I haven't actually tried it, so it's only a hypothesis at this point.

**Comment by ZevEisenberg** [comment]
Sadly, I don't think it worked:

```
(lldb) vi label
error: error: use of undeclared identifier 'CFTypeRef'
Traceback (most recent call last):
  File "/Users/zev/Projects/chisel/fblldb.py", line 83, in runCommand
    command.run(args, options)
  File "/Users/zev/Projects/chisel/commands/FBVisualizationCommands.py", line 183, in run
    _visualize(arguments[0])
  File "/Users/zev/Projects/chisel/commands/FBVisualizationCommands.py", line 151, in _visualize
    if fb.evaluateBooleanExpression('(unsigned long)CFGetTypeID((CFTypeRef)' + target + ') == (unsigned long)CGImageGetTypeID()'):
  File "/Users/zev/Projects/chisel/fblldbbase.py", line 84, in evaluateBooleanExpression
    return (int(evaluateIntegerExpression('(BOOL)(' + expression + ')', printErrors)) != 0)
  File "/Users/zev/Projects/chisel/fblldbbase.py", line 76, in evaluateIntegerExpression
    output = evaluateExpression('(int)(' + expression + ')', printErrors).replace('\'', '')
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by kastiglione** [comment]
Thanks. I'll try out your sample project.

**Comment by kastiglione** [comment]
There is a chain of errors. I fixed a couple, but I hit a second type related error and so I'm going to stop and think. The two type reference errors are `CFTypeRef`, and `CGRect`. For `CFTypeRef`, I replaced it with `void *`, but there isn't a generic replacement for `CGRect`. I'm going to try to figure out why these types (and presumably others) aren't available when having lldb evaluate objc expressions from a Swift app.

**Comment by ZevEisenberg** [comment]
Any chance it's something like having to call `expr import CoreGraphics`?

**Comment by kastiglione** [comment]
Thank it is possible that Chisel needs to do that. It will probably have to be `expr @import CoreGraphics` since Chisel commands generate objc. If this does work, I guess we'll need some central location to manage and execute the imports, on behalf of commands.
