### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by choungchamnab** [facebook/chisel#174]
When I'm trying to import fblldb.py, I got this error : 

> Traceback (most recent call last):
  File "/usr/local/opt/chisel/libexec/fblldb.py", line 10, in <module>
    import lldb
ImportError: No module named lldb

**Comment by kastiglione** [comment]
Can you paste the output from running these commands *from the lldb prompt*:

```
script import sys; print sys.executable
```

```
script import sys; print sys.path
```

**Comment by shengyangyu** [comment]
thank you,I'm try to @kastiglione solve the error.

**Comment by zhengyaoyuan** [comment]
1. /usr/bin/python
2.['/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A', '/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/Library/Python/2.7/site-packages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC', '.']
How can fix the problem? @kastiglione

**Comment by zhengyaoyuan** [comment]
1. /usr/bin/python

1.  ['/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A', '/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/Library/Python/2.7/site-packages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC', '.']

1. How can fix the problem? @kastiglione

**Comment by zhengyaoyuan** [comment]
- ==> Using the sandbox
==> Downloading https://github.com/facebook/chisel/archive/1.5.0.tar.gz
Already downloaded: /Users/zhengyaoyuan/Library/Caches/Homebrew/chisel-1.5.0.tar.gz
==> Caveats
Add the following line to ~/.lldbinit to load chisel when Xcode launches:
  command script import /usr/local/opt/chisel/libexec/fblldb.py
==> Summary
🍺  /usr/local/Cellar/chisel/1.5.0: 24 files, 122.3KB, built in 2 seconds

- ~ zhengyaoyuan$ command script import /usr/local/opt/chisel/libexec/fblldb.py

- Script started, output file is import
Traceback (most recent call last):
  File "/usr/local/opt/chisel/libexec/fblldb.py", line 10, in <module>
    import lldb
ImportError: No module named lldb

Script done, output file is import   

- @kastiglione

**Comment by vin-zhou** [comment]
Got the same issue. Any way to solve it ?

**Comment by kastiglione** [comment]
@zhengyaoyuan 

> `command script import /usr/local/opt/chisel/libexec/fblldb.py`

this needs to be **run in lldb**.

**Comment by zhengyaoyuan** [comment]
@kastiglione   thx! It works!
