### ISSUE TITLE
Unable To Add Border to UIView

### ISSUE THREAD

**Issue by jackrobson** [facebook/chisel#186]
Forgive me if I am not doing this right.

(lldb) pviews 0x7faee840af00
<_UILayoutGuide: 0x7faee840af00; frame = (0 736; 0 0); hidden = YES; layer = <CALayer: 0x608000023ae0>>
(lldb) border 0x7faee840af00
error: error: use of undeclared identifier 'CGFloat'
error: error: use of undeclared identifier 'CGColorRef'
error: expected ']'
to match this '['

PS. This is in a Swift project

**Comment by idrisr** [comment]
try running this first:

expr @import UIKit

if that fixes your issue, you can add

command alias uikit expr @import UIKit

to your lldbinit file and in the future you'll have to only write uikit before
having the functionality available

**Comment by aboelbisher** [comment]
Hi
I have the same problem and running : expr @import UIKit .
gave me this error : error: <EXPR>:3:2: error: expected an attribute name

**Comment by kastiglione** [comment]
if it's a swift project, you'll probably want to run `expr import UIKit`, or you can stick with the objective-c syntax by using `expr -l objc -- @import UIKit`.
