### ISSUE TITLE
Can't import custom commands

### ISSUE THREAD

**Issue by shmidt** [facebook/chisel#190]
I was following docs, and added

```
command script import /usr/local/opt/chisel/libexec/fblldb.py
script fblldb.loadCommandsInDirectory('/Users/dshmidt/Documents/Scripts/LLDB/Chisel/')
```

to my `.lldbinit `file.

However, I'm getting following error when running `command source ~/.lldbinit`:
```
Script done, output file is import
-bash: /Users/dshmidt/.lldbinit: line 49: syntax error near unexpected token `('
-bash: /Users/dshmidt/.lldbinit: line 49: `script fblldb.loadCommandsInDirectory('/Documents/Scripts/LLDB/Chisel/')'
```

If I just run lldb, then it shows:
```
File "<input>", line 1
SyntaxError: can't assign to operator
```

**Comment by kastiglione** [comment]
You shouldn't need to run `command source ~/.lldbinit`, that should happen automatically by lldb when it starts. However if you do want to run this, it needs to be from lldb's command prompt, but it looks like you are running this from the command line. Let me know if this helps sort things out.

**Comment by shmidt** [comment]
@kastiglione I was using `command source ~/.lldbinit` just to reload this file in terminal. Here I just provided its output, as it gives more clear error message, then when I run lldb.

**Comment by kastiglione** [comment]
`command source ~/.lldbinit` is an lldb command, it must be run from the lldb command prompt (`(lldb) `), not from the command line. Running it from the command line will run the `script` command (which is for capturing a shell session's input and output).

**Comment by kastiglione** [comment]
I believe my last answer should clear things up, but if not feel free to re-open with further updates.

**Comment by shmidt** [comment]
I still have this problem.
So from what I understand, this error comes from 'import lldb' line.
I removed all Python versions except system one, and 'import lldb' totally works in REPL, so I have no idea why it doesn't work in Chisel.
