### ISSUE TITLE
wivar does't work with internal properties of UIKit objects

### ISSUE THREAD

**Issue by kos9kus** [facebook/chisel#191]
I try to create a watch point and hang it up to UIView's hidden property 
*self is UIViewController object*
```bash
wivar self.view _hidden
error: error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=1, address=0x0).
The process has been returned to the state before expression evaluation.
Traceback (most recent call last):
  File "/usr/local/opt/chisel/libexec/fblldb.py", line 83, in runCommand
    command.run(args, options)
  File "/usr/local/Cellar/chisel/1.5.0/libexec/commands/FBDebugCommands.py", line 43, in run
    ivarSize = int(fb.evaluateExpression(ivarSizeCommand), 0)
TypeError: int() can't convert non-string with explicit base
```
Is command syntax corrected I have written!?

**Comment by kastiglione** [comment]
Have you confirmed that `UIView` has an ivar named `_hidden`? One way to check is to run this lldb command, which will probably print a lot of info, but does include the list of ivars for the class.

```
language objc class-table dump -v ^UIView$
```

**Comment by kastiglione** [comment]
Chisel should be improved to handle the case where there is no ivar, and print out an error message.
