### ISSUE TITLE
Chisel not loading because of errors

### ISSUE THREAD

**Issue by sryze** [facebook/chisel#193]
I installed chisel via`brew install chisel` but my ~/.lldbinit didn't seem to be working (none of thee chisel commands were found). I manually executed `command source ~/.lldbinit` from LLDB to check if there are any errors as suggested somewhere else and this is what I got:

```
(lldb) command source ~/.lldbinit
Executing commands in '/Users/szx/.lldbinit'.
(lldb) # ~/.lldbinit
command script import /usr/local/opt/chisel/libexec/fblldb.py
error: module importing failed: No module named six
  File "temp.py", line 1, in <module>
  File "/usr/local/opt/chisel/libexec/fblldb.py", line 10, in <module>
    import lldb
  File "/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python/lldb/__init__.py", line 98, in <module>
    import six
```

(I think this needs to be mentioned in the installation instructions.)

After installing this module via `pip install six` there is another error now:

```
(lldb) command source ~/.lldbinit
Executing commands in '/Users/szx/.lldbinit'.
# ~/.lldbinit
command script import /usr/local/opt/chisel/libexec/fblldb.py
Traceback (most recent call last):
  File "/usr/local/opt/chisel/libexec/fblldb.py", line 25, in __lldb_init_module
    loadCommandsInDirectory(commandsDirectory)
  File "/usr/local/opt/chisel/libexec/fblldb.py", line 39, in loadCommandsInDirectory
    loadCommand(module, command, commandsDirectory, fileName, fileExtension)
  File "/usr/local/opt/chisel/libexec/fblldb.py", line 52, in loadCommand
    lldb.debugger.HandleCommand('script ' + functionName + ' = sys.modules[\'' + module.__name__ + '\']._loadedFunctions[\'' + key + '\']')
AttributeError: 'NoneType' object has no attribute 'HandleCommand'
```

**Comment by kastiglione** [comment]
> (I think this needs to be mentioned in the installation instructions.)

Is this referring to installing the `six` module?

I've seen the issue with `six` before, but that was due to corporate IT installing its own python and it not having the `six` module. On a stock macOS with stock Xcode, the `six` module is installed 

```
lldb.debugger.HandleCommand('script ' + functionName + ' = sys.modules[\'' + module.__name__ + '\']._loadedFunctions[\'' + key + '\']')
AttributeError: 'NoneType' object has no attribute 'HandleCommand'
```

That's unusual, apparently `lldb.debugger` is null (`None`). I haven't seen this before.

How come you are running `command source ~/.lldbinit`? Shouldn't that happen by default? I don't think this is the cause of the problem, but I'm just asking in case there's any more details to learn.

**Comment by sryze** [comment]
I was running `command source ~/.lldbinit` just to see the errors because I couldn't understand why none of the chisel commands worked, normally it's included from my `~/.lldbinit`:

```
command script import /usr/local/opt/chisel/libexec/fblldb.py
```

Regarding the `six` module error, it seems that I have installed Python via Homebrew, could it be the reason?

Right now everything is working again, I don't know what's changed. I guess I should close this.

**Comment by kastiglione** [comment]
> Regarding the `six` module error, it seems that I have installed Python via Homebrew, could it be the reason?

That combined with path order and such.

The readme should be updated to mention six, since it is the one module that comes up from time to time.

**Comment by NikolayShubenkovProgSchool** [comment]
@sryze 
yes. this is the reason. Location of Chisel for homebrew is like /usr/local/Cellar/chisel/1.6.0/libexec/fblldb.py 
so this line should be as the following:
command script import /usr/local/Cellar/chisel/1.6.0/libexec/fblldb.py 

to check location of home-brew packet please use command:
brew info chisel

**Comment by hujiawei** [comment]
@NikolayShubenkovProgSchool 
tks 
`command script /usr/local/Cellar/chisel/2.0.0/libexec/fblldb.py`
this works for me.

**Comment by hujiawei** [comment]
cause this path have no six package `/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/site-packages` you should install six package here
