### ISSUE TITLE
bmessage -[ViewController viewDidLoad] can't make a breakpoint.

### ISSUE THREAD

**Issue by feikang** [facebook/chisel#194]
i use command bmessage -[ViewController viewDidLoad] ,xcode console show 
Setting a breakpoint at -[ViewController viewDidLoad] with condition (void*)object_getClass((id)$r0) == 0x001f9738
Breakpoint 2: where = GrowingTest`-[ViewController viewDidLoad] at ViewController.m:23, address = 0x00104940
but it does't stop . just run as without breakpoint .

**Comment by feikang** [comment]
it works on iphone,but does't work on simulator。

**Comment by kastiglione** [comment]
does your view controller happen to be using KVO?

**Comment by feikang** [comment]
no, i found that when i hook this method with runtime ,it work .
