### ISSUE TITLE
Config?

### ISSUE THREAD

**Issue by 3DLudi** [facebook/chisel#196]
Wow =)
~2900 OreDict entries for Chisel blocks...
YUNo OreDict config?

**Comment by kastiglione** [comment]
I'm not familiar with OreDict. Are you looking for https://github.com/Chisel-Team/Chisel?

**Comment by 3DLudi** [comment]
Desc:
Chisel is a collection of LLDB commands to assist in the debugging of iOS apps.

Opps!  Sorry.  You sir... are correct.
Please ignore.  Just me being sloppy.
