### ISSUE TITLE
border doesn't work with swift 3

### ISSUE THREAD

**Issue by aboelbisher** [facebook/chisel#208]
Hi.
am trying to border a view (using swift 3 and Xcode 9.1) , but it keeps giving me this error : 
error: error: use of undeclared identifier 'CGFloat'
error: error: use of undeclared identifier 'CGColorRef'
error: expected ']'
to match this '['

**Comment by kastiglione** [comment]
thanks, I'll take a look

**Comment by xhruso00** [comment]
Reboot fix this issue for me.

**Comment by xhruso00** [comment]
try in console 
e @import AppKit or
e @import UIKit

**Comment by aboelbisher** [comment]
reboot what ? my macbook ? or just the Xcode ?

**Comment by aboelbisher** [comment]
rebooting didn't fix the issue 
and importing gave me an error : 
error: <EXPR>:3:2: error: expected an attribute name
@import UIKit

and also #import UIKit gave the error :
error: error: use of undeclared identifier 'CGFloat'
error: error: use of undeclared identifier 'CGColorRef'
error: expected ']'
to match this '['

after calling "border self.view"

**Comment by kastiglione** [comment]
This should be fixed by #232.
