### ISSUE TITLE
Release Latest Version To Homebrew

### ISSUE THREAD

**Issue by mohamede1945** [facebook/chisel#221]
Currently, the latest version at homebrew is 1.6.0 http://formulae.brew.sh/formula/chisel, would you please release 1.7.1?

**Comment by keith** [comment]
See https://github.com/Homebrew/homebrew-core/pull/22450/ for progress on this

**Comment by mohamede1945** [comment]
thank you

**Comment by kastiglione** [comment]
Homebrew has been updated. Thanks!
