### ISSUE TITLE
Attempted to Dereference An Invalid ObjC Object

### ISSUE THREAD

**Issue by danielchangsoojones** [facebook/chisel#226]
I am trying to run the fa11y command, but I get this error. I can't seem to figure it out or find any resources to fix this. Here is the complete error:

> (lldb) fa11y C
> error: error: Execution was interrupted, reason: Attempted to dereference an invalid ObjC Object or send it an unrecognized selector.
> The process has been returned to the state before expression evaluation.
> error: error: use of undeclared identifier 'None'
> Traceback (most recent call last):
>   File "/usr/local/opt/chisel/libexec/fblldb.py", line 83, in runCommand
>     command.run(args, options)
>   File "/usr/local/Cellar/chisel/1.7.1/libexec/commands/FBAccessibilityCommands.py", line 89, in run
>     self.accessibilityGrepHierarchy(rootView, arguments[0])
>   File "/usr/local/Cellar/chisel/1.7.1/libexec/commands/FBAccessibilityCommands.py", line 71, in accessibilityGrepHierarchy
>     accessibilityElementsCount = fb.evaluateIntegerExpression('[%s count]' % accessibilityElements)
>   File "/usr/local/opt/chisel/libexec/fblldbbase.py", line 88, in evaluateIntegerExpression
>     output = evaluateExpression('(int)(' + expression + ')', printErrors).replace('\'', '')
> AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by kastiglione** [comment]
thanks I'll look into this

**Comment by kastiglione** [comment]
It looks like a private method used by `fa11y` and `pa11y` is no longer present. `_accessibilityElementsInContainer:topLevel:includeKB:`

**Comment by kastiglione** [comment]
cc @bartoszj who had previously contributed to these commands.
