### ISSUE TITLE
Chisel not working for me.

### ISSUE THREAD

**Issue by anil0605** [facebook/chisel#250]
Hi Team,

I have tried to run chisel with my XCode 9.4.1  I have created a file .lldbinit inside the project folder with the contents 
command script import /usr/local/opt/chisel/libexec/fblldb.py

I have checked the above file path and it's correct also. Please find the below screenshot if that helps.

<img width="1393" alt="screen shot 2018-10-08 at 5 48 08 pm" src="https://user-images.githubusercontent.com/41462220/46622416-60504500-cb22-11e8-9a58-671a7261ddfc.png">

<b>Could anyone please help. I really want to use all of these debugging commands in my project.</b>

**Comment by DerekSelander** [comment]
@anil0605, importing can fail for a number of reasons.  Try running that `command script import ...` inside the LLDB console while your app is running and check out the potential error message.  If you get an error message that will be give the Chisel maintainers more context for a fix.

**Comment by kastiglione** [comment]
> .lldbinit inside the project folder with the contents

As far as I know this does not work. Can you try adding the `command script import` command to your `.lldbinit` in your home directory (`~/.lldbinit`)?

**Comment by 279961172** [comment]
(lldb) script import /path/to/fblldb.py
  File "<input>", line 1
    import /path/to/fblldb.py
           ^
SyntaxError: invalid syntax
(lldb) 

Not support python 3.7?

**Comment by kastiglione** [comment]
You're missing `command`. It should `command script import`

**Comment by 279961172** [comment]
(lldb) command script import /path/to/fblldb.py
error: module importing failed: invalid pathname
(lldb)

**Comment by 279961172** [comment]
> You're missing `command`. It should `command script import`

(lldb) command script import /path/to/fblldb.py
error: module importing failed: invalid pathname
(lldb)

**Comment by kastiglione** [comment]
`/path/to/fblldb.py` is a placeholder in the documentation, you have to substitute your real path to wherever fblldb.py is on your computer.
