### ISSUE TITLE
Chisel not working; 'sys' is not defined

### ISSUE THREAD

**Issue by acoomans** [facebook/chisel#254]
Added `command script import /usr/local/opt/chisel/libexec/fblldb.py` to ~/.lldbinit; not working.

Running `command script import /usr/local/opt/chisel/libexec/fblldb.py` directly into lldb gives:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NameError: name 'sys' is not defined
```

**Comment by acoomans** [comment]
Solved by importing sys manually in `~/.lldbinit`:

```
command script import sys
command script import /usr/local/opt/chisel/libexec/fblldb.py
```

**Comment by chizcake** [comment]
You saved me!

**Comment by kastiglione** [comment]
Thanks for the report. I've opened #255 to resolve the issue.
