### ISSUE TITLE
Supports Xcode 11 with Python3 instead of Python2

### ISSUE THREAD

**Issue by dreampiggy** [facebook/chisel#262]
See [Xcode 11 Beta Release Notes](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_beta_release_notes#3319453)

> LLDB’s Python scripting is now based on Python 3. If you are using Python extensions that aren’t compatible with Python 3, they will break. To help with the transition, you can run in Python 2 mode by setting a default:

> defaults write com.apple.dt.lldb DefaultPythonVersion 2
> Python 2 support will be removed in the future. (47806994)

**Comment by LoSenTrad** [comment]
??? 不懂 怎么处理?xcode11不能使用chisel

**Comment by dorentus** [comment]
> ??? 不懂 怎么处理?xcode11不能使用chisel

@LoSenTrad 

Until this issue is resolved, you can run the following command once in Terminal:

    defaults write com.apple.dt.lldb DefaultPythonVersion 2

Then LLDB will use old Python 2 and chisel will be happy to run in Xcode (for now).

**Comment by LoSenTrad** [comment]
> > ??? 不懂 怎么处理?xcode11不能使用chisel
> 
> @LoSenTrad
> 
> Until this issue is resolved, you can run the following command once in Terminal:
> 
> ```
> defaults write com.apple.dt.lldb DefaultPythonVersion 2
> ```
> 
> Then LLDB will use old Python 2 and chisel will be happy to run in Xcode (for now).

OK! The problem has been solved !  thanks~

**Comment by dreampiggy** [comment]
Yes. We can trun the Python 2 support for now.
I write this issue here, just want to give chisel a hint to start migration to Python 3 :)

**Comment by chenjiangchuan** [comment]
I spent some time letting chisel support Python [chisel support Python 3](https://github.com/chenjiangchuan/chisel)

**Comment by revolter** [comment]
@chenjiangchuan, Why didn't you fork this? This way, you could also open a PR here.

**Comment by kolinkrewinkel** [comment]
Thanks to #266, we should be ready to go on Xcode 11!

**Comment by nrbrook** [comment]
Please release!
