### ISSUE TITLE
'pca' command not work

### ISSUE THREAD

**Issue by oschanger** [facebook/chisel#264]
I tried 'pca' command on backboard/Springboard/my app, all not work.

(lldb) pca
error: error: Execution was interrupted, reason: signal SIGABRT.
The process has been returned to the state before expression evaluation.

This not work too

(lldb) po [NSString stringWithCString:(char *)CARenderServerGetInfo(0, 2, 0)]
error: Execution was interrupted, reason: internal ObjC exception breakpoint(-3)..
The process has been returned to the state before expression evaluation.

**Comment by kastiglione** [comment]
Which version of the OS? Maybe the private function was removed or changed.

**Comment by kastiglione** [comment]
@kolinkrewinkel maybe `pca` should be removed. I doubt anyone uses it.

**Comment by oschanger** [comment]
i'm using it, lol. My version is iphone8p 12.1.2
i reversed QuartzCore and see the function is still there.
But i don't know any other way to invoke this

**Comment by oschanger** [comment]
i'm tring to understand mechanism of render-server. so it's useful to me

**Comment by kastiglione** [comment]
It's great that you're getting use of it. I think the vast majority of chisel users wouldn't use it.

One thing about chisel is it has commands for many things that can be simple aliases, and `pca` is one of them. You could add this to your `~/.lldbinit`:

```
command alias pca p (char*)CARenderServerGetInfo(0, 2, 0)
```

As far as getting this to work, try fiddling with the values. It's a private function, maybe they added a parameter, or removed a parameter. Also maybe it doesn't return `char *` any more.
