### ISSUE TITLE
Setup wrong in Xcode11.0

### ISSUE THREAD

**Issue by Lenhulk** [facebook/chisel#270]
(lldb) command source ~/.lldbinit
command script import /usr/local/opt/chisel/libexec/fblldb.py
error: module importing failed: Missing parentheses in call to 'print'. Did you mean print('Whoops! You are missing the <' + arg.argName + '> argument.')? (fblldb.py, line 98)
  File "temp.py", line 1, in <module>

**Comment by kastiglione** [comment]
Being fixed in #266

**Comment by kolinkrewinkel** [comment]
Fixed by #266!
