### ISSUE TITLE
New release please!

### ISSUE THREAD

**Issue by revolter** [facebook/chisel#274]
Trying to install with `brew install --HEAD chisel` errors out:

```
==> Cloning https://github.com/facebook/chisel.git
Updating /Users/iulian/Library/Caches/Homebrew/chisel--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 7782bdd Make chisel compatible with Python 3 (#266)
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - PATENTS
```

**Comment by hotchner** [comment]
+1

**Comment by zhang28602** [comment]
+1

**Comment by nahuel-zapata** [comment]
I have the same issue 🙁

**Comment by elfenlaid** [comment]
+1

**Comment by joshavant** [comment]
Just a heads up: If you want to sidestep Homebrew and install Chisel manually, you can do this:

```
git clone git@github.com:facebook/chisel.git /usr/local/opt/chisel
```

then add the following line to your `~/.lldbinit` file:

```
command script import /usr/local/opt/chisel/fblldb.py
```

**Comment by Ad1991** [comment]
Either what @joshavant said or you can just paste the PAENTS file from any older releases like [this one](https://github.com/facebook/chisel/blob/1.8.1/PATENTS) in `~/Library/Caches/Homebrew/chisel--git/` folder once you receive the error and run `brew install --HEAD chisel` command again. This workaround will allow you keep managing `chisel` via `homebrew`.

**Comment by revolter** [comment]
@Ad1991, But it will **not** install the latest version.

**Comment by Ad1991** [comment]
@revolter: I may be missing something but why not?  After pasting the file, you are still executing `brew install --HEAD chisel` which will install the latest revision.

Below are my logs after parting the PATENTS file:

```
$ brew install --HEAD chisel
==> Cloning https://github.com/facebook/chisel.git
Updating ~/Library/Caches/Homebrew/chisel--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 7782bdd Make chisel compatible with Python 3 (#266)
==> make -C Chisel install PREFIX=/usr/local/Cellar/chisel/HEAD-7782bdd/lib LD_DYLIB_INSTALL_NAME=/usr/local/opt/chisel/lib/Chisel.framework/Chisel
==> Caveats
Add the following line to ~/.lldbinit to load chisel when Xcode launches:
  command script import /usr/local/opt/chisel/libexec/fblldb.py
==> Summary
🍺  /usr/local/Cellar/chisel/HEAD-7782bdd: 32 files, 281.4KB, built in 8 seconds
Removing: ~/Library/Caches/Homebrew/chisel--1.8.1.mojave.bottle.tar.gz... (65.3KB)
```

**Comment by revolter** [comment]
Oh, I previously found some messages related to `brew`'s `HEAD` option stating that it tries to install the latest tagged commit, not the latest commit 😐.

**Comment by kolinkrewinkel** [comment]
Should be fixed soon, sorry about the wait! https://github.com/Homebrew/homebrew-core/pull/50571

**Comment by kolinkrewinkel** [comment]
Should be good to go now with a `brew upgrade`. Let me know if you have any issues!

**Comment by chenrui333** [comment]
@kolinkrewinkel maybe good time to cut a new release again? https://github.com/facebook/chisel/issues/311
