### ISSUE TITLE
error: (lldb) command script import /usr/local/opt/chisel/libexec/fblldb.py

### ISSUE THREAD

**Issue by wulinfeng198810** [facebook/chisel#283]
```
(lldb) command script import /usr/local/opt/chisel/libexec/fblldb.py
error: module importing failed: Missing parentheses in call to 'print'. Did you mean print('Whoops! You are missing the <' + arg.argName + '> argument.')? (fblldb.py, line 98)
  File "temp.py", line 1, in <module>
```

Hi, how to deal with it?

**Comment by lucidstream** [comment]
me too

**Comment by joey-bing** [comment]
I meet the same problem in macOS Catalina 10.15.2, Xcode 11.3.1.

**Comment by iandundas** [comment]
this is fixed for me since updating to the latest chisel (2.0.0)

**Comment by kolinkrewinkel** [comment]
Yep, this is solved by updating to have Python 3 support! There's a new release coming later today (https://github.com/Homebrew/homebrew-core/pull/59799), so I'd recommending updating via brew in around 8 hours so you get the latest and greatest!
