### ISSUE TITLE
error: module importing failed: invalid pathname

### ISSUE THREAD

**Issue by zkhalapyan** [facebook/chisel#284]
Do we need to update brew after deb751e596ad74425a1b293d7b98b625cac9d94d? Currently running `brew update; brew install chisel` doesn't fetch latest, so `command script import /usr/local/opt/chisel/libexec/fbchisellldb.py` path doesn't resolve, since the installed file is still called `fblldb.py`. 

Thought could install head, but doesn't seem like this is working. I can manually resolve the path to `fblldb.py` in my `~/.lldbinit`, but wanted to see what's the right way of doing this?

```
% brew install --head chisel
Warning: chisel  is already installed
The currently linked version is 2.0.0
You can use `brew switch chisel ` to link this version.
```

**Comment by zkhalapyan** [comment]
Also realized, the version installed by brew doesn't have Python3 support, so seems pretty old. It's installing version 2.0.0.

**Comment by zkhalapyan** [comment]
Alright, seems like I got what happened: 

* Python 3 support was in 2.0.0, but xrange fix (d5f155d) wasn't included, so it's still breaking 😢
* There hasn't been a new release since the naming change (deb751e) and therefore brew vs. repo are out of sync.

I would recommend making a new minor release 2.0.1 with the new commits; to make it simple, I have drafted the release notes 😎maybe @kolinkrewinkel or @kastiglione could take up on it! 🙏

# Release Name: It's Not Halting (2.0.1)

Pushing a minor release to fix a Python 3 issue (d5f155d) as well as to sync brew with latest naming convention (deb751e), see below for more details:

* Replace xrange with range to fix Python 3 issue (d5f155d) - thanks to @kastiglione!
* Renaming all fblldb* to fbioslldb* to avoid conflict with lldb (deb751e) - thanks to @aadsm
* New copy command that can be used to copy any NSURL or NSData to the host machine (0c9ee31) - awesome new tool by Chris Ellsworth.

---
Once a release is created, need to update homebrew formula, similar to this: https://github.com/Homebrew/homebrew-core/commit/b12704fb179a822b406669faff020cfb5e4e273e

**Comment by kolinkrewinkel** [comment]
I'll take a pass at fixing this as soon as I can (probably Friday or Monday)! Thanks for digging into it @zkhalapyan!

**Comment by nikans** [comment]
Any progress here? :)

**Comment by Linyok** [comment]
I also have this question in my Xcode Version 11.4.1

**Comment by Hastewave** [comment]
The problem is still relevant

**Comment by Tliens** [comment]
Successfully! 👏

1、直接下载zip包
2、解压缩
3、打开 /usr/local/Cellar/ 
4、将下载好的所有文件放到这个文件夹中
5、.lldbinit文件中修改为
```
# ~/.lldbinit
command script import /usr/local/Cellar/chisel/libexec/fblldbbase.py
```

**Comment by zkhalapyan** [comment]
![200](https://user-images.githubusercontent.com/796815/89941696-3c536400-dbd0-11ea-814d-a7b271bbd2f2.gif)

**Comment by kolinkrewinkel** [comment]
I’ll try and get an update to brew out later today, thanks for the reminder!

**Comment by kolinkrewinkel** [comment]
https://github.com/Homebrew/homebrew-core/pull/59799 in progress!

**Comment by kolinkrewinkel** [comment]
Should be good now, sorry it took so long!

**Comment by zkhalapyan** [comment]
yay, thanks!
