### ISSUE TITLE
bmessage  cause a error message

### ISSUE THREAD

**Issue by sunbohong** [facebook/chisel#292]
```
(lldb) bmessage +[KKDic load]
Setting a breakpoint at +[NSObject load] with condition (void*)object_getClass((id)$x0) == 0x000000010071f878
error: Function name regular expression could not be compiled: repetition-operator operand invalid
```

**Comment by kolinkrewinkel** [comment]
Hi @sunbohong , sorry for the (very large) delay in getting to this. Thanks for catching this, seems like a really useful fix! A few comments I think would be great to address before proceeding:
- Would be awesome to update the title of the commit to something more descriptive of the change itself for people looking through the commit log in the future.
