### ISSUE TITLE
fb.evaluateIntegerExpression converting incorrectly to hex?

### ISSUE THREAD

**Issue by KingOfBrian** [facebook/chisel#54]
I'm working on getting a count of a method, and it returns a large number, 0x7fffffff (2147483647).  The value 2147483647 is getting passed to int('2147483647', 16), which is not correct, it should be int ('2147483647', 10).   Am I missing something?

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by idrisr** [comment]
I believe @KingOfBrian is correct and it should be base 10. Created this pull request: https://github.com/facebook/chisel/pull/119.

**Comment by kastiglione** [comment]
Fixed in #236
