### ISSUE TITLE
Break out a libChisel

### ISSUE THREAD

**Issue by kastiglione** [facebook/chisel#62]
I mentioned this in a [recent comment](https://github.com/facebook/chisel/pull/55#issuecomment-65961831), but I'd like to get more feedback on this idea.

Many of the commands end up marshaling a bunch of expressions back and forth between LLDB's python interpreter and the target app, but this has proven to be slowish at times. For example the manual path `pvc` is a fair bit slower than the path that uses `+[UIViewController _printHierarchy]`.

I believe there could be a solid usability and maintainability improvement if we divided the architecture into two halves:
1. Code that interacts with LLDB's interfaces.
2. Code that interacts with the app's objects and data.

I think we could bundle a dynamic library and have Chisel load that into the app via ~~`target modules add`~~`process load`. This adds some complexity, but the benefits would be faster interaction & feedback with Chisel commands, and also I think this would smooth the path toward adding testing to the project. Plus not having to write objc encoded in python strings is an improvement.

cc @arigrant @mattjgalloway @mmmulani @dstnbrkr @KingOfBrian @kolinkrewinkel

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by kastiglione** [comment]
This did happen in #197
