### ISSUE TITLE
Specify objc++ where necessary for Swift support

### ISSUE THREAD

**Issue by kastiglione** [facebook/chisel#74]
In https://github.com/facebook/chisel/pull/68#issuecomment-71319049 @moreindirection pointed out that in the context of Swift, many lldb commands called internally from Chisel commands need to be updated to explicitly specify the language as `objc++`.

See #73

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by kastiglione** [comment]
Fixed by #121.
