### ISSUE TITLE
PVC command error in Xcode 6.3 beta1

### ISSUE THREAD

**Issue by banxi1988** [facebook/chisel#77]
test on a simple iOS One View Application
error message as follows.
```Console
(lldb) pvc
error: error: use of undeclared identifier 'CGRect'
error: missing '[' at start of message send expression
error: expected ']'
note: to match this '['
error: 3 errors parsing expression
[Error getting description.]

(lldb) 
```

**Comment by kastiglione** [comment]
Thanks! Have you tried beta 2 which came out yesterday? If you do try it, mind updating this issue if it is resolved? Hopefully it's just a beta bug.

**Comment by mattjgalloway** [comment]
Closing this out as it works in Xcode 6. It must have been an issue in the first beta. Presumably works now because we use `_printHierarchy`.
