### ISSUE TITLE
Issues running in Swift

### ISSUE THREAD

**Issue by nickkjordan** [facebook/chisel#80]
I am getting errors because my expressions are running in Swift despite the [`evaluateExpressionValueInFrameLanguage`](https://github.com/facebook/chisel/blob/abcbb93abe22d98b273c981c71c96ece80286af6/fblldbbase.py#L49) function

Typical error statement:

error: expected ',' separator
(int)((BOOL)((unsigned long)CFGetTypeID((CFTypeRef)(shape)) == (unsigned long)CGImageGetTypeID()))

Is there something I'm missing here?  I'm just calling `visualize <value>`

**Comment by donshefer** [comment]
I'm seeing something similar in my Swift project:

(lldb) caflush
error: <EXPR>:1:22: error: expected ',' separator
(void)[CATransaction flush]

**Comment by kastiglione** [comment]
Thanks for the reports! I will try to take a look at this soon.

**Comment by yxztj** [comment]
Hi, I'm also seeing this error:
(lldb) pviews
error: <EXPR>:1:20: error: expected ',' separator
(id)[(id)[UIWindow keyWindow] recursiveDescription]

**Comment by kastiglione** [comment]
@yxztj I just tried running `pviews` using the "Master-Detail Application" template that comes with Xcode. I could not reproduce the error you've reported. I am using the latest Xcode GM, 6.3.2 GM. If you're able to try the GM and let me know whether the GM fixes this for you, that would be great. Or, using whichever version you have installed currently, could you try creating a new project based on the "Master-Detail Application" template and let me know if `pviews` is broken? Thanks!

**Comment by kastiglione** [comment]
@donshefer I just tried `caflush` using Xcode 6.3.2 GM, and could not reproduce the error you reported. When you update to 6.3.2, if you try `caflush` on your Swift project and it still fails, I would love to know and investigate more. Thanks!

**Comment by kastiglione** [comment]
@nickkjordan I am seeing different errors when I run `visualize`. I'll look into them. I was calling `visualize` on a view. Were you calling it on a image, view, or layer?

**Comment by nickkjordan** [comment]
This is bad, but I can't quite remember at this point.  I *think* it was on a layer though, because I remember doing some animations around then

**Comment by ignat980** [comment]
I am also getting this error. 
```
(lldb) caflush
error: <EXPR>:1:22: error: expected ',' separator
(void)[CATransaction flush]
                     ^
                    ,
```
I am running the command within a swift context, and I have no idea how to change the language from swift inside the debugger. I think this is related to #74 and #68 .

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by alireza** [comment]
Seems like the problem only occurs in Swift projects in which lldb expects swift commands.

Basically, in the python scripts commands sent to the debugger using lldb.debugger.HandleCommand are all in objc. They won't work when lldb debugger is in swift mode.

**Comment by stkent** [comment]
Same issue and output as @ignat980 above.

**Comment by schwarrrtz** [comment]
Same issue and output as @ignat980 and @stkent. Similar issues with flicker.

**Comment by theonepa1** [comment]
```self``` is of type ```UICollectionViewController```. Ran mask and got following error.

```(lldb) mask self.view```
error: error: use of undeclared identifier 'self'
error: 1 errors parsing expression
Traceback (most recent call last):
  File "/usr/local/opt/chisel/libexec/fblldb.py", line 81, in runCommand
    command.run(args, options)
  File "/usr/local/Cellar/chisel/1.2.0/libexec/commands/FBDisplayCommands.py", line 55, in run
    layer = viewHelpers.convertToLayer(args[0])
  File "/usr/local/opt/chisel/libexec/fblldbviewhelpers.py", line 51, in convertToLayer
    if fb.evaluateBooleanExpression('[(id)%s isKindOfClass:(Class)[CALayer class]]' % viewOrLayer):
  File "/usr/local/opt/chisel/libexec/fblldbbase.py", line 69, in evaluateBooleanExpression
    return (int(evaluateIntegerExpression('(BOOL)(' + expression + ')', printErrors)) != 0)
  File "/usr/local/opt/chisel/libexec/fblldbbase.py", line 61, in evaluateIntegerExpression
    output = evaluateExpression('(int)(' + expression + ')', printErrors).replace('\'', '')
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by webdevotion** [comment]
@ultramiraculous, from what I saw in #121 you expected this ticket to be resolved as wel.  
Today I still get an error when running for example `mask self.view` in `lldb`.
Got rid of my Homebrew install and using a clone from the main branch.

```bash
(lldb) mask self.view
error: error: use of undeclared identifier 'self'
error: 1 errors parsing expression
error: error: use of undeclared identifier 'None'
error: 1 errors parsing expression
error: <EXPR>:1:13: error: expected ',' separator
(void)[None removeFromSuperview]
            ^
           ,
error: <EXPR>:1:22: error: expected ',' separator
(void)[CATransaction flush]
                     ^
                    ,
error: error: use of undeclared identifier 'None'
error: 1 errors parsing expression
Traceback (most recent call last):
  File "/...path-to-chisel.../chisel/fblldb.py", line 79, in runCommand
    command.run(args, options)
  File "/...path-to-chisel.../chisel/commands/FBDisplayCommands.py", line 93, in run
    viewHelpers.maskView(viewOrLayer, options.color, options.alpha)
  File "/...path-to-chisel.../chisel/fblldbviewhelpers.py", line 24, in maskView
    origin = convertPoint(0, 0, viewOrLayer, window)
  File "/...path-to-chisel.../chisel/fblldbviewhelpers.py", line 46, in convertPoint
    fromLayer = convertToLayer(fromViewOrLayer)
  File "/...path-to-chisel.../chisel/fblldbviewhelpers.py", line 51, in convertToLayer
    if fb.evaluateBooleanExpression('[(id)%s isKindOfClass:(Class)[CALayer class]]' % viewOrLayer):
  File "/...path-to-chisel.../chisel/fblldbbase.py", line 69, in evaluateBooleanExpression
    return (int(evaluateIntegerExpression('(BOOL)(' + expression + ')', printErrors)) != 0)
  File "/...path-to-chisel.../chisel/fblldbbase.py", line 61, in evaluateIntegerExpression
    output = evaluateExpression('(int)(' + expression + ')', printErrors).replace('\'', '')
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by tracicot** [comment]
I'm seeing the same issues. Executing `show view` results in:
`error: <EXPR>:1:19: error: expected ',' separator
(void)[scrollView setHidden:0]
                  ^
                 ,
error: <EXPR>:1:22: error: expected ',' separator
(void)[CATransaction flush]
                     ^
                    ,`

**Comment by albertstartup** [comment]
Using show and hide work when using clone from main branch. Try cloning the latest version @tracicot 
mask still produces same error as @webdevotion

**Comment by kastiglione** [comment]
I think this be closed now. Swift interop has been improved, and we can create new issues for specific issues as they arise.
