### ISSUE TITLE
border <view> not working on osx

### ISSUE THREAD

**Issue by pvinis** [facebook/chisel#81]
i have an NSView* view and i try to border it but i get this.
(lldb) border view
error: use of undeclared identifier 'UIColor'
error: 1 errors parsing expression

**Comment by kastiglione** [comment]
Thanks for the report. Can you run the below command from your app's lldb console and let me know what the output is?

```
script print lldb.debugger.GetSelectedTarget().GetTriple()
```

**Comment by pvinis** [comment]
this.
x86_64h-apple-macosx

**Comment by pvinis** [comment]
i actually changed the border function to use NSColor instead of UIColor and its ok now, but i thought it should choose by itself. maybe i have to change everything UI* to NS*?

**Comment by kastiglione** [comment]
When did you install or last updated Chisel? We should support this arch as of January 5th, see #69.

**Comment by kastiglione** [comment]
Here's the code that chooses whether to use `UIColor` or `NSColor`:

https://github.com/facebook/chisel/blob/c5e57331805f9f1d67d88eb61603a75575ce8ab9/commands/FBDisplayCommands.py#L48-L58

**Comment by pvinis** [comment]
i installed it with brew.
% brew info chisel
chisel: stable 1.1.0
https://github.com/facebook/chisel
/usr/local/Cellar/chisel/1.1.0 (18 files, 112K) *
  Built from source
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/chisel.rb
==> Caveats
Add the following line to ~/.lldbinit to load chisel when Xcode launches:
  command script import /usr/local/opt/chisel/libexec/fblldb.py

**Comment by pvinis** [comment]
oh.. i dont have that code.. mine was [UIColor ....
is the version in brew that old?

**Comment by kastiglione** [comment]
Oh! We need to submit an update to brew. In the meantime, you might want to try installing from git, which should be pretty straightforward.

**Comment by pvinis** [comment]
yep. i will do that. thanks. will it also work for UIWindow stuff etc?

**Comment by kastiglione** [comment]
It should, but I'm not entirely sure. The Mac support was provided by @kolinkrewinkel in #45. Please do file any issues you run into and we can look at fixes.

**Comment by pvinis** [comment]
thanks again.

**Comment by kastiglione** [comment]
You're welcome! Thanks for filing.
