### ISSUE TITLE
Adding ComponentKit's debugging commands to Chisel

### ISSUE THREAD

**Issue by MarcoSero** [facebook/chisel#85]
It would be nice to have something to print the components' hierarchy in Chisel.

Wouldn't 

    pcomponents

be better of

    po [CKComponentHierarchyDebugHelper componentHierarchyDescription]

**Comment by kastiglione** [comment]
Yes, it would!

hey @natansh hurry up already!

**Comment by kastiglione** [comment]
@MarcoSero Check out #86

**Comment by MarcoSero** [comment]
That was quick! Thank you.
