### ISSUE TITLE
'vs' command broken?

### ISSUE THREAD

**Issue by palcalde** [facebook/chisel#88]
XCode prints this, anyone knows how to fix it?

Traceback (most recent call last):
  File "/usr/local/Cellar/chisel/1.2.0/libexec/fblldb.py", line 81, in runCommand
    command.run(args, options)
  File "/usr/local/Cellar/chisel/1.2.0/libexec/commands/FBFlickerCommands.py", line 60, in run
    walker = FlickerWalker(object)
  File "/usr/local/Cellar/chisel/1.2.0/libexec/commands/FBFlickerCommands.py", line 67, in __init__
    self.handler = inputHelpers.FBInputHandler(lldb.debugger, self.inputCallback)
  File "/usr/local/Cellar/chisel/1.2.0/libexec/fblldbinputhelpers.py", line 16, in __init__
    self.inputReader = lldb.SBInputReader()
AttributeError: 'module' object has no attribute 'SBInputReader'

**Comment by kastiglione** [comment]
Thanks for the report! I'll look into this and get back to you, hopefully soon :stuck_out_tongue_winking_eye:

**Comment by palcalde** [comment]
Thank you! I used to use this command a lot to jump between siblings and superviews. It was great. And a lot faster than the built in tree hierarchy view in the debugger :-)

**Comment by kastiglione** [comment]
@palcalde Which version of Xcode are you using? With Xcode 6.2 / lldb-320.4.160, the problem is that the `SBInputReader` class is not exposed through the `lldb` module. I haven't tried Xcode 6.3, hopefully the missing class is a temporary regression.

**Comment by palcalde** [comment]
@kastiglione I'm using 6.3, tho this command has been broken since last 3/4 months. I think since XCode 6.0. I've created a #92  that fixes it, instead of using SBInputReader which, as you mention, is not accesible anymore I used the standard stdin. I tested it and seems to work fine. Let me know what you think.

**Comment by kastiglione** [comment]
Fixed by #92
