### ISSUE TITLE
got error at ' isMac = runtimeHelpers.isMacintoshArch()'

### ISSUE THREAD

**Issue by nealsun** [facebook/chisel#94]
run any command, got this error
Traceback (most recent call last):
  File "/usr/local/opt/chisel/libexec/fblldb.py", line 81, in runCommand
    command.run(args, options)
  File "/usr/local/Cellar/chisel/1.2.0/libexec/commands/FBPrintCommands.py", line 104, in run
    isMac = runtimeHelpers.isMacintoshArch()
AttributeError: 'module' object has no attribute 'isMacintoshArch'

**Comment by kastiglione** [comment]
Thanks for the report. I'll look into this today.

**Comment by kastiglione** [comment]
@nealsun Did you install from git, homebrew, or some other way?

**Comment by nealsun** [comment]
@kastiglione Yes, I installed from homebrew

**Comment by kastiglione** [comment]
Ok I'll install from homebrew and see what's up.

**Comment by jernejstrasner** [comment]
Same thing here.

**Comment by kastiglione** [comment]
Ok thanks. Will get to this!

**Comment by idrisr** [comment]
@jernejstrasner @nealsun can you please do a `brew info chisel` in the terminal and post your results.

**Comment by jernejstrasner** [comment]
@idrisr sorry for the late reply, but this does not happen anymore in the latest version.

**Comment by kastiglione** [comment]
Thanks everyone!
